steps:
- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    git config -f .gitmodules submodule.myiworlds_myiworlds.url https://source.cloud.google.com/myiworlds/github_myiworlds_myiworlds
    git submodule init
    git submodule update

# Install all Dev dependecies
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']

# Lint the affected apps in dev mode
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'affected:lint']

# Build the affected apps in dev mode
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'affected:build']

# Test the affected apps in dev mode
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'affected:test']

