steps:
# Install all Dev dependecies
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']

# Lint the affected apps in dev mode
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'affected:lint']

# Build the affected apps in dev mode
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'affected:build']

# Test the affected apps in dev mode
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'affected:test']

