import { SHARED_TYPES } from './sharedTypes';

export const CIRCLE_TYPES = {
  ...SHARED_TYPES,
  STRING: 'STRING' as 'STRING',
  BOOLEAN: 'BOOLEAN' as 'BOOLEAN',
  NUMBER: 'NUMBER' as 'NUMBER',
  BIG_NUMBER: 'BIG_NUMBER' as 'BIG_NUMBER',
  DATE: 'DATE' as 'DATE',
  DATA: 'DATA' as 'DATA',
  GEO_POINT: 'GEO_POINT' as 'GEO_POINT',
  LINE: 'LINE' as 'LINE',
  LINES: 'LINES' as 'LINES',
  UI: 'UI' as 'UI',
  MEDIA_FONT_ICON: 'MEDIA_FONT_ICON' as 'MEDIA_FONT_ICON',
  EDGE: 'EDGE' as 'EDGE',
  EDGE_NODE: 'EDGE_NODE' as 'EDGE_NODE',
  QUERY_GET_DOCUMENT_BY_ID: 'QUERY_GET_DOCUMENT_BY_ID' as 'QUERY_GET_DOCUMENT_BY_ID',
  QUERY_GET_DOCUMENTS_BY_IDS: 'QUERY_GET_DOCUMENTS_BY_IDS' as 'QUERY_GET_DOCUMENTS_BY_IDS',
  QUERY_GET_DOCUMENTS_BY_FILTERS: 'QUERY_GET_DOCUMENTS_BY_FILTERS' as 'QUERY_GET_DOCUMENTS_BY_FILTERS',
};
