export const SHARED_TYPES = {
  UPDATED: 'UPDATED' as 'UPDATED',
  CREATED: 'CREATED' as 'CREATED',
  VIEWED: 'VIEWED' as 'VIEWED',
  VIEWED_BY_IDS: 'VIEWED_BY_IDS' as 'VIEWED_BY_IDS',
  PERMISSION_DENIED: 'PERMISSION_DENIED' as 'PERMISSION_DENIED',
  DOES_NOT_EXIST: 'DOES_NOT_EXIST' as 'DOES_NOT_EXIST',
};
