export const SHARED_TYPES = {
  UPDATED: 'UPDATED',
  CREATED: 'CREATED',
  VIEWED: 'VIEWED',
  VIEWED_BY_IDS: 'VIEWED_BY_IDS',
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  DOES_NOT_EXIST: 'DOES_NOT_EXIST',
};
