fragment CircleHeaderFragment on Circle {
  id
  collection
  cached
  pii
  autoUpdate
  parent {
    id
  }
  copiedFrom {
    id
  }
  copiedFromClone
  slug
  public
  passwordRequired
  type
  tags
  title
  subtitle
  description
  media {
    id
    type
    title
    string
    data
  }
  creator {
    id
    username
  }
  owner {
    id
    username
  }
  viewers {
    id
    username
  }
  editors {
    id
    username
  }
  ui {
    id
    title
    data
    lines {
      id
      title
      data
    }
  }
  layouts {
    id
    title
    data
  }
  dateCreated
  dateUpdated
}
